In [3]:
#You r managing the electronics section of a store.you need to track the sales of 3 products:Headphones,smartwatches,and speakers over 4 days(monday to thursday)
#row 0:headphone
#row 1:smartwatches
#row 2:speakers

In [4]:
import numpy as np
dily_sales = np.array([[1500],[3000],[5000]])
print(dily_sales.shape)
print(dily_sales.ndim)

(3, 1)
2


In [5]:
sold = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(sold.shape)
print(sold.ndim)
print(sold)

(3, 4)
2
[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [6]:
print("Adding bonus: ")
print(sold + 2)

Adding bonus: 
[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [7]:
print(dily_sales * sold)
#print(np.dot(sold,dily_sales))

[[15000 22500 12000 18000]
 [15000 21000 12000 18000]
 [10000 15000 10000 20000]]


In [8]:
#Access the sale data for Smartwatches(row1) for all 4 days#slicing and indexing
#Acess the sales data for all product for the first 2 days
#Access sales of speakers on thursday using double indexing
print(sold[0])
print("All product of the first 2 days: ")
print(sold[:, :2])
print("Sales of speakers on thrusday:")
print(sold[:, 3:])



[10 15  8 12]
All product of the first 2 days: 
[[10 15]
 [ 5  7]
 [ 2  3]]
Sales of speakers on thrusday:
[[12]
 [ 6]
 [ 4]]


In [9]:
#RESHAPING AND LINESPACE
#Flatten the 3*4daily sales array into 1D array of 12 element using .reshape()
print("Reshapen sales array:")
print(sold.reshape(-1))
#Convert the sales data into 2*6 matrix
print("2 * 6:")
print(sold.reshape(2,6))
#Using np.linspace to create an array of 10 equal inervall between 0 and 100 to represent "Discount percentage"
array = np.linspace(1,100,10)
print("Discount Percentage:")
print(array)


Reshapen sales array:
[10 15  8 12  5  7  4  6  2  3  2  4]
2 * 6:
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]
Discount Percentage:
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [15]:
#The random module
#Use np.random.randint to generate a new 3*4 array of "Predicted Sales "for the next week with values ranging from 0 to 20.
predicted_sales = np.random.randint(0,20,size=(3,4))
print("Predicted sales from 0 t0 20")
print(predicted_sales)
#Generate a random array of 5 numbers between 0 and 1 using np.random.randint
random = np.random.randint(0,1,5)
print("Random from 0 to 1: ")
print(random)
#Use np.sum() to find:total items sold over all 4 days,total items sold for each product(Sum across rows)
print("Total sold over 4 days: ")
print(np.sum(sold,axis=0))

Predicted sales from 0 t0 20
[[ 2  5 11  5]
 [ 7  5 11  7]
 [10 19 13  5]]
Random from 0 to 1: 
[0 0 0 0 0]
Total sold over 4 days: 
[17 25 14 22]
