In [2]:
import numpy as np
mark = np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(mark)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [10]:
#TASK1 Metadata discover
print(mark.shape)
#total number of element
print(mark.size)
#datatype of element
print(mark.dtype)
#TASK2:INDEXING AND SLICING
#extract all mark for 2nd student
print("All mark for 2nd student:")
print(mark[1:2,:])
#extract all marks of 3rd subject across all student
print("All marks of 3rd subject across all student:")
print(mark[:,2:])
#find specific mark for student 1 in subject 2
print("Specific mark for student 1 in subject 2:")
print(mark[0:1,1:2])

(5, 3)
15
int64
All mark for 2nd student:
[[45 60 55]]
All marks of 3rd subject across all student:
[[90]
 [55]
 [95]
 [35]
 [75]]
Specific mark for student 1 in subject 2:
[[85]]


In [ ]:
#Task b:Means and Average
#Calculate the average marks for each student
avg_marks = np.sum(mark) / 
#Calculate the average marks for each subject

#Task b2: Filtering top performance
#Identiffy and display students whose average marks are >=80

#Task b3: Global Adjustement
#The college student decides to add 5 graces marks to every subject for every student Update the array using broadcasting
