In [27]:
import numpy as np


CAMPUS ELECTRICITY USAGE ANALYSIS

In [28]:
#Create a numpy array electricity using np.random.randint
electricity = np.random.randint(120, 650, size=(4, 7))
print(electricity)
#Value between 120 and 650
#Shape 4,7
#Task 2: print the following attributes of the array:shape,number of dimension,total number of element,and data type
print(electricity.shape)
print(electricity.ndim)
print(electricity.size)
print(electricity.dtype)

[[537 487 272 196 316 153 605]
 [374 328 597 199 371 149 156]
 [502 362 296 429 227 499 591]
 [500 226 190 333 387 284 554]]
(4, 7)
2
28
int32


In [29]:
#Task B1:Hostel-wise Metrics 
#Find the average electricity usage per hostel,eh maximum usage per hostel,and identify which hostel has the highest average usage
average_per_hostel = np.mean(electricity, axis=0)
print(np.round(average_per_hostel,2))
print(np.max(average_per_hostel))
#Task B2:Day-wise metrics
#Calculate the total electicity consumption per day and identify the day with the highest total campus consumption(must choose the correct axis value for each operation)
total = (np.sum(electricity,axis=0))
print(total)
print("Highest Total campus consumption:")
print(np.max(total))

[478.25 350.75 338.75 289.25 325.25 271.25 476.5 ]
478.25
[1913 1403 1355 1157 1301 1085 1906]
Highest Total campus consumption:
1913


In [30]:
#POLICY RULE: if electricity usage on any day is greater than 550 units,a 20% surcharge is applies
#Task C1
#Create a new array penalized_usage such that :value > 550 -> multiplied by 1.20
#all other value remain unchanged
#must use np.where.no loop allowed
penalized_usage = np.where(electricity > 550,electicity*1.20,electricity)
print(penalized_usage)

NameError: name 'electicity' is not defined

In [ ]:
#Task D1:Thinking task
#Compare each hostel's daily usage with its own weekly average.Create a boolean matrix where:True:Above hostel average,false below or equal to hostel average
#requires broadcasting of a (4,)array across(4,7)
compare = np.where(electricity > average_per_hostel,1,0)
print(compare)


[[1 0 1 0 1 0 0]
 [1 1 0 1 0 0 1]
 [1 0 0 0 1 1 0]
 [0 0 1 1 0 0 0]]


In [ ]:
#Task E1
#Reshape the electricity data into a single row representing weekly usage (Shape: 1* 28)
rshape = np.reshape(electricity,-1)
print("Reshape 1 * 28")
print(rshape)
#TASK E2:Reshape the same data into 2 rows and 14 columns.Ensure no data is lost or duplicated
rshape1 = rshape.reshape(2,14)
print("Reshape 2 * 14:")
print(rshape1)

Reshape 1 * 28
[640 169 497 281 553 212 396 591 578 146 590 242 162 642 607 221 166 186
 634 485 468 433 208 281 395 209 223 500]
Reshape 2 * 14:
[[640 169 497 281 553 212 396 591 578 146 590 242 162 642]
 [607 221 166 186 634 485 468 433 208 281 395 209 223 500]]


In [32]:
#TASK F1:Copy vs view
#Create ref_backup = electicity
ref_backup = electricity
electricity[0:0] = 60
#Create safe_backup = electicity.copy()
safe_backup = electricity.copy()
#Modify one value in the original electricity array
#electricity[0:0] = 60
#Observe which backup change
print(ref_backup)
print(safe_backup)

[[537 487 272 196 316 153 605]
 [374 328 597 199 371 149 156]
 [502 362 296 429 227 499 591]
 [500 226 190 333 387 284 554]]
[[537 487 272 196 316 153 605]
 [374 328 597 199 371 149 156]
 [502 362 296 429 227 499 591]
 [500 226 190 333 387 284 554]]
