In [2]:
import numpy as np
mark = np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(mark)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [3]:
#TASK1 Metadata discover
print(mark.shape)
#total number of element
print(mark.size)
#datatype of element
print(mark.dtype)
#TASK2:INDEXING AND SLICING
#extract all mark for 2nd student
print("All mark for 2nd student:")
print(mark[1:2,:])
#extract all marks of 3rd subject across all student
print("All marks of 3rd subject across all student:")
print(mark[:,2:])
#find specific mark for student 1 in subject 2
print("Specific mark for student 1 in subject 2:")
print(mark[0:1,1:2])

(5, 3)
15
int64
All mark for 2nd student:
[[45 60 55]]
All marks of 3rd subject across all student:
[[90]
 [55]
 [95]
 [35]
 [75]]
Specific mark for student 1 in subject 2:
[[85]]


In [10]:
#Task b:Means and Average
#Calculate the average marks for each student
avg_marks_student = np.mean(mark, axis=1)
print(np.round(avg_marks_student,2))
#Calculate the average marks for each subject
avg_marks_subject = np.mean(mark, axis=0)
print(np.round(avg_marks_student,2))
#Task b2: Filtering top performance
#Identify and display students whose average marks are >=80
greater = np.where(avg_marks_student >= 80)
print(greater)
#Task b3: Global Adjustement
#The college student decides to add 5 graces marks to every subject for every student Update the array using broadcasting


[84.33 53.33 91.67 35.   70.  ]
[84.33 53.33 91.67 35.   70.  ]
(array([0, 2]),)


In [ ]:
#Task C1: Pass/fail
#Create a status matrix where :.Mark >=50 1(Pass).Mark < 50 0(Fail)
result = np.where(avg_marks_student< 50,0 ,1)
print(result)
#Data Cleaning:To standarize failing grades,replace all mark below 40 with a value of 0
clean = np.where(avg_marks_student < 40,0,avg_marks_student)


[1 1 1 0 1]


In [ ]:
#Task D1:Grade allocation .Apply a grading system based on student average
#Avg > 85: Grade A(Score: 10)
#Avg >=70: Grade B(Score: 8)
#Avg >=50: Grade C (Score: 6)
#Below 50: No grade(Score: 0)(Use nested conditional logic within numpy)
grade = np.where(avg_marks_student < 50,0,np.where(avg_marks_student < 70,6),np.where(avg_marks_student < 85,8,10))
#disp2 = np.

Grade B


In [ ]:
#Task E1: The "Copy vs View "Challenge
#Create a backup of the marks array
backup = mark.copy()
#Modify the original array(eg: set marks[0,0] = 0)
mark[0,0] = 0
#Check if the backup array changed or remained original
print(backup)
print("Modified Marks in the original:")
print(mark)
#Why is it dangerous backup = marks instead of backup = marks.copy


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
Modified Marks in the original:
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
