In [ ]:
import numpy as np
#1D array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#2D array
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Built in function
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#Arraay property
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [ ]:
#Type conversion
arr = np.array([1.2,2.5,3.7])
arr_int = arr.astype(int)
print(arr_int)

[1 2 3]


In [20]:
#Indexing and slicing
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [21]:
#Slicing
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30]


In [22]:
#2D indexing
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [24]:
#Slicing
print(mat[:,1])#column 1

[2 5 8]


In [25]:
#Copy array
a = np.array([1,2,3])
b = a.copy()
b[0] = 99#only b is updated tht why we use .copy so it won't be copied in a
print(a)
print(b)

[1 2 3]
[99  2  3]


In [ ]:
#operation on numpy
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [28]:
#Can add and multiply array by any number
print(a + 10)
print(a * 2)

[11 12 13]
[2 4 6]


In [29]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


In [31]:
#Boolean indexing
arr = np.array([10,20,30,40,50])
print(arr[arr>25])
print(arr>25)

[30 40 50]
[False False  True  True  True]


In [34]:
#Broadcasting rule
#Numpy automatically expands smaller arrays
arr = np.array([1,2,3,4])
print(arr + 10)
mat = np.array([[1,2,3],[4,5,6]])
print(mat + 10)

[11 12 13 14]
[[11 12 13]
 [14 15 16]]


In [35]:
row = np.array([1,2,3])
print(mat + row)

[[2 4 6]
 [5 7 9]]


In [ ]:
#Matrix multipliction
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
#not element wise multiplication
print(np.dot(A,B)) #may lead to error bc numpy will brodcast it if we dont use .dot

[[19 22]
 [43 50]]


In [38]:
#Transpase matrix
print(A.T)

[[1 3]
 [2 4]]


In [41]:
#Random module
np.random.rand(5)

array([0.54834582, 0.7240223 , 0.14346314, 0.52317589, 0.96743539])

In [42]:
np.random.rand(3,3)

array([[0.74157526, 0.71802906, 0.95189541],
       [0.63125447, 0.00469104, 0.74278519],
       [0.51598443, 0.18120859, 0.07948711]])

In [44]:
np.random.randint(1,100,10)

array([45, 60, 74, 37, 25, 21, 32, 29, 87,  2], dtype=int32)

In [46]:
#Reshape array
arr = np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#You r managing the electronics section of a store.you need to track the sales of 3 products:Headphone,smartwatches,and speakers over 4 days(monday to thursday)
#row 0:headphone
#row 1:smartwatches
#row 2:speakers
