In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
print(np.sum(arr))

21


In [3]:
#Sum element of each column
print(np.sum(arr,axis=0))

[5 7 9]


In [5]:
#Sum of each row
print(np.sum(arr,axis=1))

[ 6 15]


In [ ]:
#Where in numpy
ar = np.array([10,-5,20,-3,15])
#If and else(condition,true,false)
result = np.where(ar < 0,0 ,ar)
print(result)

[10  0 20  0 15]


In [10]:
arr = np.array([1,2,3,4,5])
result = np.where(arr % 2 !=0, -1 , arr)
print(result)

[-1  2 -1  4 -1]


In [11]:
marks = np.array([45,78,32,90,55])
status = np.where(marks >= 50,1,0)
print(status)

[0 1 0 1 1]


In [15]:
#finding mean value
data = np.array([10,20,30,40,50])
mean_val = np.mean(data)
result = np.where(data > mean_val,mean_val,data)
print(result)

[10. 20. 30. 30. 30.]


In [ ]:
#Applying where in 2d array
mat = np.array([[10,60,30],[80,20,90]])
result = np.where(mat >= 50,1,0)
print(result)

[[0 1 0]
 [1 0 1]]
